image: node:latest
stages:
  - setup
  - test

cache:
  paths:
    - node_modules/

setup:
  stage: setup
  script:
    - npm install
  tags:
    - docker

test:
  stage: test
  script:
    - npm run test ./test/Discord/